Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - bin/*

Metrics/PerceivedComplexity:
  Exclude:
    - bin/*

Layout/LineLength:
  Max: 150
  Exclude:
    - bin/*
    - spec/services/**/*.rb

Metrics/BlockLength:
  Max: 50

